# Generated by Django 5.2.8 on 2025-11-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_code',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
